TRAFFIC_LIGHT_INT_PATH = "traffic_light_int"
LABEL_TRAIN_PATH = "data/train_label"
LABEL_TEST_PATH = "data/test_label"
IMG_TRAIN_PATH = "data/train"
IMG_TEST_PATH = "data/test"
IMAGE_SIZE_X = '288'
IMAGE_SIZE_Y = '288'
TRAIN_NUM = int(8e3)
TEST_NUM = int(2e3)
TICK_COUNT = TRAIN_NUM + TEST_NUM 
IMAGE_PATH = './_out_tick'
BATCH_SIZE = 256
EPOCH = 5